### ISSUE TITLE
How to repack on Windows?

### ISSUE THREAD

**Issue by Allgames-Alis** [hhyyrylainen/GodotPckTool#13]
First of all, I'm not good at English.
Please forgive me because I am using machine translation.

Isn't Repack meant to turn unpacked files (in folders) into ".pck files" again?
Please tell me how to repack the folder containing the unpacked files into the ".pck file" again.

When I tried "godotpcktool.exe -p sample.pck -a r -f new.pck", "sample.pck" and "new.pck" did not become the same file.

I am very sorry for the basic question, but I would be very happy if you could reply.

**Comment by hhyyrylainen** [comment]
What did you see instead? For me running `godotpcktool -p Thrive.pck -a r -f new.pck` results in `new.pck` having the same contents as `Thrive.pck` and if I remove the original `Thrive.pck` and replace it with the new file the game still works. So even though the files aren't exactly the same, they are functionally the same.

**Comment by Allgames-Alis** [comment]
This won't repack the modified files (eg translation files), right?
It seems like I just copied the original Thrive.pck as new.pck.

What i want to do:
1. Unpack the original ".pck file"
2. Edit the extracted file (for example, text editing or font replacement).
  * This extracted folders/files is in the "Extract folder".
3. Repack the "Extract folder" containing the edited file as "New.pck".
4. Use new .pck in the game.

**Comment by hhyyrylainen** [comment]
So you don't actually want the repack action? The repack action is for taking an existing .pck file and potentially filtering the contents with size and name filters and then creating a new .pck file. What you actually sound like you want is the option to create a new .pck from a folder contents.

So you need to first extract:
https://github.com/hhyyrylainen/GodotPckTool#extracting-contents

then edit the files

and finally create a new .pck from the extracted folder you edited:
https://github.com/hhyyrylainen/GodotPckTool#adding-content

**Comment by Allgames-Alis** [comment]
Thank you very much.
Finally I understood the flow of repacking.
Thank you very much for your precious time.
