### ISSUE TITLE
nlohmann/json.hp dependency

### ISSUE THREAD

**Issue by Draco18s** [hhyyrylainen/GodotPckTool#14]
This project depends on [this one](https://github.com/nlohmann/json) and not mentioned in readme or how to fetch/install it.

**Comment by hhyyrylainen** [comment]
It's included as a git submodule. The readme says "Also don't forget to init git submodules." but doesn't give an explicit command. If someone wants to add the git submodule init command into the readme to make it more visible, feel free, but I'll close this issue as when followed the build instructions work.

**Comment by Draco18s** [comment]
Doh! Silly me, I did a download-zip and managed to miss the submodules reference.
👍
