### ISSUE TITLE
It doesn't imports images. Only the import file.

### ISSUE THREAD

**Issue by IAMSTANDARD** [hhyyrylainen/GodotPckTool#22]
I used it on a pck of a web build. But it did not extract the images, only the import files for the images.

**Comment by hhyyrylainen** [comment]
Duplicate of: https://github.com/hhyyrylainen/GodotPckTool/issues/7

**Comment by IAMSTANDARD** [comment]
But it seems like they didn't reach at any conclusion?

**Comment by hhyyrylainen** [comment]
But this is still the same exact feature request, of wanting to do further processing on the files rather than just extracting the files that are contained in a .pck.
