### ISSUE TITLE
TOC padding is wrong

### ISSUE THREAD

**Issue by sergeikrasnikov** [hhyyrylainen/GodotPckTool#23]
The table of content padding calculation is wrong

In the file 
[PckFile.cpp](https://github.com/hhyyrylainen/GodotPckTool/blob/e07e0e7cbc712c63881ae2c124e75473fba37fd5/src/pck/PckFile.cpp#L138)
the lines 137--139
```
        const size_t pathToWriteSize =
            entry.Path.size() + (entry.Path.size() % PadPathsToMultipleWithNULLS);
        const size_t padding = pathToWriteSize - entry.Path.size();
```
The middle line should be 
`entry.Path.size() + (PadPathsToMultipleWithNULLS - entry.Path.size() % PadPathsToMultipleWithNULLS)`

For reference, see the function 
`static int _get_pad(int p_alignment, int p_n) `
in
[editor_export_platform.cpp](https://github.com/godotengine/godot/blob/eba33c67b49905973ee7c81a709046415a41e205/editor/export/editor_export_platform.cpp#L49)

**Comment by hhyyrylainen** [comment]
So the problem is that the padding amount is reverse of what it should be?

**Comment by hhyyrylainen** [comment]
Doing an excel file with various values, I noticed that the corrected math you suggested results in the correct padded lengths, but when the length is exactly right it ends up adding 4 extra padding bytes, though maybe that is actually required to have at least one terminating null?

I'll do a PR to test if the new math works fine or if there is potentially a problem.
